"""Approved size and count bounds for Milestone 10A evidence."""

from __future__ import annotations

MAX_DOCUMENT_REQUEST_BYTES = 100_000
MAX_RAW_TEXT_BYTES = 100_000
MAX_NORMALIZED_TEXT_BYTES = 100_000
MAX_CHUNKS_PER_DOCUMENT = 64
CHUNK_SIZE_CODE_POINTS = 800
CHUNK_OVERLAP_CODE_POINTS = 100
MAX_SOURCE_URI_CHARS = 2000
MAX_CORPUS_KEY_CHARS = 128
MAX_TITLE_CHARS = 300
MAX_CLAIMS_PER_DRAFT = 20
MAX_EVIDENCE_IDS_PER_CLAIM = 5
MAX_EVIDENCE_ITEMS_TO_DRAFTER = 8
MAX_EVIDENCE_CHARS_PER_ITEM_IN_DRAFT = 1_500
MAX_DRAFT_EVIDENCE_CONTEXT_BYTES = 12_000

PARSER_PLAIN_TEXT_V1 = "plain_text.normalize.v1"
PARSER_MARKDOWN_V1 = "markdown.normalize.v1"
PARSER_SEARCH_SNIPPET_V1 = "search_snippet.v1"

TRUST_UNTRUSTED = "[untrusted_source]"
TRUST_OPERATOR_CORPUS = "[operator_corpus]"
